server:
  port: 80

spring:

  datasource:
    url: jdbc:mysql://localhost/only?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true

dms:
  handle:
    scheduled:
      dev:
        check:
          status: 3
only:
  session:
    flag: true
    url: 23r3ogj
